#!/usr/bin/env python3
"""
Parse serial logs generated by the firmware and compute simple KPI:
- deadline miss rate per task
- p95/p99 of durations per task

Usage:
  python scripts/parse_logs.py logs/serial_baseline.log -o results/baseline.csv
"""
import sys
import re
import argparse
from collections import defaultdict
import statistics

LINE_RE = re.compile(r"\[(?P<ts>\d+)ms\] (?P<task>[^ ]+) end duration=(?P<dur>\d+)ms deadline=(?P<dl>\d+)ms (?P<res>HIT|MISS)")


def parse_file(path):
    tasks = defaultdict(list)
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = LINE_RE.search(line)
            if m:
                t = m.groupdict()
                task = t['task']
                dur = int(t['dur'])
                dl = int(t['dl'])
                res = t['res']
                tasks[task].append((dur, dl, res))
    return tasks


def compute_kpi(tasks):
    out = {}
    for task, records in tasks.items():
        durs = [r[0] for r in records]
        misses = sum(1 for r in records if r[2] == 'MISS')
        total = len(records)
        p95 = int(statistics.quantiles(durs, n=100)[94]) if total >= 100 else max(durs) if durs else 0
        p99 = int(statistics.quantiles(durs, n=100)[98]) if total >= 100 else max(durs) if durs else 0
        out[task] = {
            'count': total,
            'misses': misses,
            'miss_rate': misses/total if total else 0,
            'p95_ms': p95,
            'p99_ms': p99,
            'max_ms': max(durs) if durs else 0
        }
    return out


def write_csv(out, outpath):
    import csv
    with open(outpath, 'w', newline='') as csvf:
        w = csv.writer(csvf)
        w.writerow(['task','count','misses','miss_rate','p95_ms','p99_ms','max_ms'])
        for task, v in sorted(out.items()):
            w.writerow([task, v['count'], v['misses'], f"{v['miss_rate']:.3f}", v['p95_ms'], v['p99_ms'], v['max_ms']])


def main():
    p = argparse.ArgumentParser()
    p.add_argument('logfile')
    p.add_argument('-o', '--out', required=True)
    args = p.parse_args()
    tasks = parse_file(args.logfile)
    out = compute_kpi(tasks)
    write_csv(out, args.out)
    print(f"Wrote KPI to {args.out}")


if __name__ == '__main__':
    main()
